#!/bin/bash
#SBATCH --job-name="CbPyh2Tree"
#SBATCH --output=Calculate_Cb_pyh_to_tree.oe
#SBATCH -A eande106
#SBATCH -p parallel
#SBATCH -t 72:00:00
#SBATCH -N 1
#SBATCH -n 48

cd ../../processed_data/LD_pruned_trees

input_file="../../processed_data/LD_pruned_trees/LD_0.9/phy_file_LD_0.9.phy"
# The .phy file was generated by scripts/geography_trees_PCA/Calculate_Cb_vcf_to_pyh.sh

# run iqtree 
source activate tree_v2.4
iqtree -s $input_file -mset GTR -bb 1000 -T 48
