#!/bin/bash
#SBATCH --job-name="CbVCF2Pyh"
#SBATCH --output=Calculate_Cb_vcf_to_phy.out
#SBATCH -A eande106
#SBATCH -p parallel
#SBATCH -t 10:00:00
#SBATCH -N 1
#SBATCH -n 6

cd ../../processed_data/
mkdir -p LD_pruned_trees
cd LD_pruned_trees

# define input files 
input_file="../../processed_data/Cb_pruned_VCF_and_PCA/EIGESTRAT/LD_0.9/INPUTFILES/eiganstrat_input.vcf.gz"
# The LD-pruned vcf file was generated by post-gatk-nf
# https://github.com/AndersenLab/post-gatk-nf
# see examples in scripts/geography_trees_PCA/nf_Cb_pruned_VCF_and_PCA.sh

mkdir -p LD_0.9
cd LD_0.9

### vcf2phylip.py available here: https://github.com/edgardomortiz/vcf2phylip
python ../../scripts/vcf2phylip.py -i $input_file
mv eiganstrat_input.min4.phy phy_file_0.9.phy
